[package]
name = "tool"
version = "0.1.0"
edition = "2024"

[dependencies]
infobip_sdk = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"
log = "0.4"
env_logger = "0.9"
chrono = "0.4"
whatsapp = "0.1.0"
dotenv = "0.15.0"
